/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VoluntaryEnterprise;

import javax.swing.JPanel;
import javax.swing.JProgressBar;
import org.apache.log4j.Logger;

/**
 *
 * @author saisr
 */
public class MainFundRaise extends javax.swing.JPanel {

    /**
     * Creates new form VaccineManufRequests
     */
    private String healthcampName;
    private int totalAmount;
    JPanel RightPanel;
    String selectedOrg;
    static Logger log = Logger.getLogger(MainFundRaise.class.getName());

    public void addMedicinesToCart( String healthcampName, int totalAmount){
        this.healthcampName = healthcampName;
        this.totalAmount = totalAmount;
        jProgressBar1.setOrientation(JProgressBar.VERTICAL);
        jProgressBar1.setValue(totalAmount);
        jProgressBar1.setStringPainted(true);
//        jLabel1.setText(jLabel1.getText() + " " + patient_name);
//        DefaultListModel<String> defaultListModel = (DefaultListModel<String>)jList1.getModel();
//        defaultListModel.clear();
//        for(String s: Arrays.asList(medicines.split("<>"))){
//           defaultListModel.addElement(s);
//        }
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fp?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Deepak@1999");
//            Statement myStatement = con.createStatement();
//            String query1 = "select * from pharmacy_requests where patient_name = '" + patientName + "'";
//            ResultSet rs = myStatement.executeQuery(query1);
//            String status = "";
//            while (rs.next()) {
//                status = rs.getString("status");
//            }
//            if(status.equals("Completed")){
//                jButton1.setEnabled(false);
//            }
//            con.close();
//        } catch (Exception E) {
//            JOptionPane.showMessageDialog(this, E + "Error in DB call");
//        }
    }
    
    public MainFundRaise(JPanel RightPanel) {
        initComponents();
        this.RightPanel = RightPanel;
//        jList1.setModel(new DefaultListModel<>());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblApprovedorRejected = new javax.swing.JLabel();
        lblRequest1 = new javax.swing.JLabel();
        lblRequest2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 255));

        lblApprovedorRejected.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblApprovedorRejected.setForeground(new java.awt.Color(102, 153, 255));
        lblApprovedorRejected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApprovedorRejected.setText("CREATE REQUEST");

        lblRequest1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lblRequest2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblApprovedorRejected, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRequest1)
                            .addComponent(lblRequest2))))
                .addGap(469, 469, 469))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRequest1, lblRequest2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblApprovedorRejected, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRequest1)
                .addGap(186, 186, 186)
                .addComponent(lblRequest2)
                .addGap(435, 435, 435))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblApprovedorRejected;
    private javax.swing.JLabel lblRequest1;
    private javax.swing.JLabel lblRequest2;
    // End of variables declaration//GEN-END:variables
}
